import type { Metadata } from "next";
import { Inter, Montserrat, Montserrat_Alternates } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });
// const

const montserrat = Montserrat_Alternates({
  subsets: ["latin"],
  variable: "--font-monserrat",
  weight:["100", "200", "300", "400","500", "600", "700", "800", "900"]
});
// const montserrat = Montserrat({
//   subsets: ["latin"],
//   variable: "--font-monserrat",
//   weight:["100", "200", "300", "400","500", "600", "700", "800", "900"]
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${inter.className} `}>
      <body className="bg-gradient-to-r from-blue-gray-50 to-white">
        {children}
      </body>
    </html>
  );
}
